#!/bin/bash
echo "🔬 剩余劳动价值论研究工作站 🔬"
echo "======================================"
echo "当前时间: $(date '+%Y年%m月%d日 %H:%M:%S')"
echo "当前目录: $(pwd)"
echo "当前分支: $(git branch --show-current)"
echo ""
echo "第一步：同步最新内容..."
git pull origin main
echo ""
echo "第二步：当前研究状态"
git status
echo ""
echo "📚 研究目录结构："
echo "  ├── assets/pdfs/        # PDF论文 (2007, 2015, 2019)"
echo "  ├── content/legacy/     # 历史研究成果"
echo "  ├── content/journals/   # 月度研究笔记"
echo "  ├── code/matlab/        # MATLAB分析代码"
echo "  └── code/latex/         # LaTeX学术写作"
echo ""
echo "💡 提示：研究完成后运行 ./submit.sh 提交成果"
echo "======================================"
